import turtle
paper=turtle.Screen()
pencil=turtle.Turtle()
pencil.shape("turtle")
pencil.speed(25)
pencil.up()
pencil.goto(-200,-200)
pencil.down()
pencil.color('green')
pencil.begin_fill()
for loop in range(2):
  pencil.forward(400)
  pencil.left(90)
  pencil.forward(66)
  pencil.left(90)
pencil.end_fill()
pencil.up()
pencil.goto(-200,-134)
pencil.down()
pencil.color('white')
pencil.begin_fill()
for loop in range(2):
  pencil.forward(400)
  pencil.left(90)
  pencil.forward(66)
  pencil.left(90)
pencil.end_fill()
pencil.up()
pencil.goto(-200,-68)
pencil.down()
pencil.color('#F4C430')
pencil.begin_fill()
for loop in range(2):
  pencil.forward(400)
  pencil.left(90)
  pencil.forward(66)
  pencil.left(90)
pencil.end_fill()
pencil.up()
pencil.goto(0,-135)
pencil.down()
pencil.color('navy')
pencil.circle(33)
pencil.up()
pencil.goto(0, -102)
pencil.down()
pencil.dot(35)