import turtle,random
bob=turtle.Turtle()
bobspaper=turtle.Screen()
bobspaper.setup(800,800)
bob.speed(100)
#a=input('What background color do you want?')
bobspaper.bgcolor('black')
bob.color('white')
def squares(a,b):
  bob.color(b)
  bob.begin_fill()
  for i in range(4):
    bob.forward(a)
    bob.left(90)
  bob.end_fill()
def triangles(a,b):
  bob.color(b)
  bob.begin_fill()
  for i in range(3):
    bob.forward(a)
    bob.left(120)
  bob.end_fill()
def rectangles(a):
  bob.color(a)
  bob.begin_fill()
  for i in range(2):
    bob.forward(75)
    bob.left(90)
    bob.forward(200)
    bob.left(90)
  bob.end_fill()
def c(a,b):
  bob.up()
  bob.goto(a,b)
  bob.down()
def dot(a,b):
  bob.color(b)
  bob.dot(a)
def star():
  bob.begin_fill()
  bob.color('yellow')
  for i in range(5):
    bob.forward(50)
    bob.right(144)
  bob.end_fill()
c(-330,-400)
squares(260,'blue')
c(50,-400)
squares(260,'blue')
c(50,-140)
triangles(260,'red')
c(-330,-140)
triangles(260,'red')
c(-300,-250)
squares(75,'yellow')
c(-300,-380)
squares(75,'yellow')
c(-175,-400)
rectangles('brown')
c(80,-250)
squares(75,'yellow')
c(80,-380)
squares(75,'yellow')
c(205,-400)
rectangles('brown')
c(-400,-400)
for i in range(40):
  triangles(20,'green')
  bob.forward(20)
c(400,400)
dot(400,'white')
z=int(input('how many stars do you want in your night sky?'))
for i in range(z):
  c(random.randint(-400,140),random.randint(150,400))
  star()